### ISSUE TITLE
CDTB is not always up to date

### ISSUE THREAD

**Issue by Neinndall** [aLonelyNetu/PBE_NewAssetsDownloader#1]
It seems to download a lot of old assets and not the recent ones from the current update. It would be very interesting if the program classify them by days. I have checked **in today's update on December 9** and it seems that it has given 2 new assets that I have checked:
- plugins/rcp-be-lol-game-data/global/default/assets/missions/seasonstart2022_cb.season_start_2022_assets.jpg
- plugins/rcp-fe-lol-loot/global/default/mythic_essence_modal_background_image.png

**I have run it again and it seems that the program has added it to the ... 3000 assets, this is too messy.**
I don't know if I will be able to add my updated hashes that I do it manually, or you should take a look.
It would be interesting that every time the program is executed it gives you the output of the new ones, not the old ones!
I do not know if you will change its operation or apply a new feature!

Thanks!

**Comment by MaNeRz** [comment]
Hey, Thank you for your feedback.
The first time you open the program the **_Assets.txt file is generated by making a request to the latest files extracted from the live server_** and the **_NewAssets.txt file_**, insted, **_is generated by making a request to the latest files extracted from PBE_**. Then the program will replace the NewAssets.txt to Assets.txt. 
From the second time you open the program or if the Assets.txt already exist the program will make request only to latest PBE files extracted.
For the 3000 assets we have to thank Rito for the new challenges system.
I'm currently working on a new way to save the assets based on days. 😄

**Comment by Neinndall** [comment]
If I have not misunderstood, for example the PBE for tomorrow, as soon as the update is complete, I will run this program and will I get the new assets?

Edit: Today the 10th, I ran a guess_hash from CDTB, what did you find is not suggested assets? I will attach some images!

![guess_hashes_from_today](https://user-images.githubusercontent.com/66384195/145637344-4cf92cd6-13e9-4e94-bc09-d29767c022f3.JPG)
![pbe_assets](https://user-images.githubusercontent.com/66384195/145637350-8c2bc66c-8c1c-4892-bad3-a4be00d0c7df.JPG)

On the other hand, it is amazing if the program separates by days when the user just executes when the PBE patch is out!

Thanks! :3

**Comment by MaNeRz** [comment]
Hey, sorry for the late reply,
I don't know how much time CDTB needs to update.
I tried the CDTB and took a lot of time to downloads all the files and create the tree pattern so i think the guess_hash is faster if you already have the .wad and .bin files. 
The thing is i don't know how the guess_hash works and for now this program supports only the requests to the Raw files from cdragon site.
So if the site is not updated the program will download nothing. 😞 
XD I made it just to improve how my code looks like and you are giving me some cool ideas to make it better.
Have to really thank you!!! :3

**Comment by Neinndall** [comment]
Do not worry! What I do is when a patch comes out, I use a script to "suggest" the new assets, files (hashes from the game and lcu) I could give you or share more information, to try to give you ideas of how you could include great improvements! It would be a pleasure to share with you how hash works! I**f you have discord, you can contact me or we can talk over there Th3Nigh7mare#9843**
